
package com.bk.railway.servlet;

import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;

public class Constants {

    public static final String QUEUE_DATABASE = "database";
    public static final String QUEUE_ORDER = "order";
    public static final String RECORD_DATABASE = "record";
    public static final String QUERY_DATABASE = "query";
    
    public static final String RECORD_ID = "record_id";
    public static final String QUERY_ID = "query_id";
    public static final String QUERY_UPDATETIME = "query_updatetime";
    public static final String QUERY_STATUS = "status";
    
    public static final String PERSON_ID = "person_id";
    public static final String FROM_STATATION = "from_station";
    public static final String TO_STATATION = "to_station";
    public static final String GETIN_DATE = "getin_date";
    public static final String TRAIN_NO = "train_no";
    public static final String ORDER_QTY = "order_qty_str";
    public static final String ORDER_NO = "order_no";
    public static final String RECORD_STATUS = "status";
    public static final String RECORD_USERNAME = "username";

    public static final String ORDER_TASKNAME = "taskname";
    public static final String ORDER_TASKETA = "tasketa";
    // public static final SimpleDateFormat ETA_TASKRUNIME = new
    // SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ",Locale.TAIWAN);
    public static final String WEB_ENCODING = "big5";

    public static final String CANCEL_SUCCESS = "success";

    public static final Map<String, String> STATION_ID_TOMAP = new TreeMap<String, String>();
    public static final String[] STATION_ARRAY;
    public static final TreeMap<String,Integer> STATION_TO_ARRAY_INDEX = new TreeMap<String,Integer>();
    static {
        STATION_ID_TOMAP.put("004", "台東");
        STATION_ID_TOMAP.put("008", "鹿野");
        STATION_ID_TOMAP.put("009", "瑞源");
        STATION_ID_TOMAP.put("012", "關山");
        STATION_ID_TOMAP.put("015", "池上");
        STATION_ID_TOMAP.put("018", "富里");
        STATION_ID_TOMAP.put("020", "東竹");
        STATION_ID_TOMAP.put("022", "東里");
        STATION_ID_TOMAP.put("025", "玉里");
        STATION_ID_TOMAP.put("029", "瑞穗");
        STATION_ID_TOMAP.put("031", "富源");
        STATION_ID_TOMAP.put("034", "光復");
        STATION_ID_TOMAP.put("035", "萬榮");
        STATION_ID_TOMAP.put("036", "鳳林");
        // STATION_ID_TOMAP.put("037","南平");
        STATION_ID_TOMAP.put("040", "豐田");
        STATION_ID_TOMAP.put("041", "壽豐");
        STATION_ID_TOMAP.put("043", "志學");
        STATION_ID_TOMAP.put("045", "吉安");
        STATION_ID_TOMAP.put("051", "花蓮");
        STATION_ID_TOMAP.put("052", "北埔");
        STATION_ID_TOMAP.put("054", "新城");
        // STATION_ID_TOMAP.put("055","崇德");
        // STATION_ID_TOMAP.put("056","和仁");
        STATION_ID_TOMAP.put("057", "和平");
        STATION_ID_TOMAP.put("062", "南澳");
        STATION_ID_TOMAP.put("063", "東澳");
        STATION_ID_TOMAP.put("066", "蘇澳");
        STATION_ID_TOMAP.put("067", "蘇澳新");
        STATION_ID_TOMAP.put("069", "冬山");
        STATION_ID_TOMAP.put("070", "羅東");
        // STATION_ID_TOMAP.put("072","二結");
        STATION_ID_TOMAP.put("073", "宜蘭");
        // STATION_ID_TOMAP.put("074","四城");
        STATION_ID_TOMAP.put("075", "礁溪");
        STATION_ID_TOMAP.put("077", "頭城");
        // STATION_ID_TOMAP.put("079","龜山");
        // STATION_ID_TOMAP.put("080","大溪");
        // STATION_ID_TOMAP.put("081","大里");
        STATION_ID_TOMAP.put("083", "褔隆");
        STATION_ID_TOMAP.put("084", "貢寮");
        STATION_ID_TOMAP.put("085", "雙溪");
        // STATION_ID_TOMAP.put("086","牡丹");
        // STATION_ID_TOMAP.put("087","三貂嶺");
        STATION_ID_TOMAP.put("088", "侯硐");
        STATION_ID_TOMAP.put("089", "瑞芳");
        // STATION_ID_TOMAP.put("090","四腳亭");
        STATION_ID_TOMAP.put("092", "基隆");
        STATION_ID_TOMAP.put("093", "八堵");
        STATION_ID_TOMAP.put("094", "七堵");
        STATION_ID_TOMAP.put("096", "汐止");
        STATION_ID_TOMAP.put("097", "南港");
        STATION_ID_TOMAP.put("098", "松山");
        STATION_ID_TOMAP.put("100", "台北");
        STATION_ID_TOMAP.put("101", "萬華");
        STATION_ID_TOMAP.put("102", "板橋");
        STATION_ID_TOMAP.put("103", "樹林");
        // STATION_ID_TOMAP.put("104","山佳");
        STATION_ID_TOMAP.put("105", "鶯歌");
        STATION_ID_TOMAP.put("106", "桃園");
        // STATION_ID_TOMAP.put("107","內壢");
        STATION_ID_TOMAP.put("108", "中壢");
        // STATION_ID_TOMAP.put("109","埔心");
        STATION_ID_TOMAP.put("110", "楊梅");
        // STATION_ID_TOMAP.put("111","富岡");
        STATION_ID_TOMAP.put("112", "湖口");
        STATION_ID_TOMAP.put("113", "新豐");
        STATION_ID_TOMAP.put("114", "竹北");
        STATION_ID_TOMAP.put("115", "新竹");
        STATION_ID_TOMAP.put("118", "竹南");
        // STATION_ID_TOMAP.put("119","談文");
        // STATION_ID_TOMAP.put("120","大山");
        STATION_ID_TOMAP.put("121", "後龍");
        STATION_ID_TOMAP.put("123", "白沙屯");
        // STATION_ID_TOMAP.put("124","新埔");
        STATION_ID_TOMAP.put("125", "通霄");
        STATION_ID_TOMAP.put("126", "苑裡");
        // STATION_ID_TOMAP.put("127","日南");
        STATION_ID_TOMAP.put("128", "大甲");
        // STATION_ID_TOMAP.put("129","台中港");
        STATION_ID_TOMAP.put("130", "清水");
        STATION_ID_TOMAP.put("131", "沙鹿");
        // STATION_ID_TOMAP.put("132","龍井");
        STATION_ID_TOMAP.put("133", "大肚");
        // STATION_ID_TOMAP.put("134","追分");
        // STATION_ID_TOMAP.put("135","造橋");
        STATION_ID_TOMAP.put("137", "苗栗");
        STATION_ID_TOMAP.put("139", "銅鑼");
        STATION_ID_TOMAP.put("140", "三義");
        // STATION_ID_TOMAP.put("142","泰安");
        STATION_ID_TOMAP.put("143", "后里");
        STATION_ID_TOMAP.put("144", "豐原");
        STATION_ID_TOMAP.put("145", "潭子");
        STATION_ID_TOMAP.put("146", "台中");
        // STATION_ID_TOMAP.put("147","烏日");
        // STATION_ID_TOMAP.put("148","成功");
        STATION_ID_TOMAP.put("149", "彰化");
        // STATION_ID_TOMAP.put("150","花壇");
        STATION_ID_TOMAP.put("151", "員林");
        STATION_ID_TOMAP.put("153", "社頭");
        STATION_ID_TOMAP.put("154", "田中");
        STATION_ID_TOMAP.put("155", "二水");
        STATION_ID_TOMAP.put("156", "林內");
        STATION_ID_TOMAP.put("158", "斗六");
        STATION_ID_TOMAP.put("159", "斗南");
        STATION_ID_TOMAP.put("161", "大林");
        STATION_ID_TOMAP.put("162", "民雄");
        STATION_ID_TOMAP.put("163", "嘉義");
        // STATION_ID_TOMAP.put("164","水上");
        // STATION_ID_TOMAP.put("166","後壁");
        STATION_ID_TOMAP.put("167", "新營");
        // STATION_ID_TOMAP.put("169","林鳳營");
        STATION_ID_TOMAP.put("170", "隆田");
        // STATION_ID_TOMAP.put("171","拔林");
        STATION_ID_TOMAP.put("172", "善化");
        STATION_ID_TOMAP.put("173", "新市");
        STATION_ID_TOMAP.put("174", "永康");
        STATION_ID_TOMAP.put("175", "台南");
        // STATION_ID_TOMAP.put("176","保安");
        // STATION_ID_TOMAP.put("177","中洲");
        STATION_ID_TOMAP.put("178", "大湖");
        STATION_ID_TOMAP.put("179", "路竹");
        STATION_ID_TOMAP.put("180", "岡山");
        // STATION_ID_TOMAP.put("181","橋頭");
        STATION_ID_TOMAP.put("183", "楠梓");
        // STATION_ID_TOMAP.put("184","左營");
        STATION_ID_TOMAP.put("185", "高雄");
        STATION_ID_TOMAP.put("186", "鳳山");
        // STATION_ID_TOMAP.put("187","後庄");
        STATION_ID_TOMAP.put("188", "九曲堂");
        STATION_ID_TOMAP.put("190", "屏東");
        // STATION_ID_TOMAP.put("193","西勢");
        // STATION_ID_TOMAP.put("194","竹田");
        STATION_ID_TOMAP.put("195", "潮州");
        STATION_ID_TOMAP.put("197", "南州");
        STATION_ID_TOMAP.put("199", "林邊");
        // STATION_ID_TOMAP.put("200","佳冬");
        STATION_ID_TOMAP.put("203", "枋寮");
        // STATION_ID_TOMAP.put("204","加祿");
        STATION_ID_TOMAP.put("211", "大武");
        STATION_ID_TOMAP.put("213", "瀧溪");
        STATION_ID_TOMAP.put("215", "金崙");
        STATION_ID_TOMAP.put("217", "太麻里");
        STATION_ID_TOMAP.put("219", "知本");
        STATION_ID_TOMAP.put("220", "康樂");
        // STATION_ID_TOMAP.put("223","大慶");
        // STATION_ID_TOMAP.put("232","十分");
        // STATION_ID_TOMAP.put("235","平溪");
        // STATION_ID_TOMAP.put("248","內灣");
        // STATION_ID_TOMAP.put("256","車埕");
        // STATION_ID_TOMAP.put("280","新烏日");
        STATION_ID_TOMAP.put("288", "新左營");
        
        STATION_ARRAY = STATION_ID_TOMAP.keySet().toArray(new String[0]);
        for(int i = 0;i < STATION_ARRAY.length;i++) {
            STATION_TO_ARRAY_INDEX.put(STATION_ARRAY[i], Integer.valueOf(i));
        }
    }

    private static final TreeSet<String> MAJOR_STOP_STATION = new TreeSet<String>();
    public static final String[] MAJOR_STOP_STATION_ARRAY;
    public static final TreeMap<String,Integer> MAJOR_STOP_STATION_TO_ARRAY_INDEX = new TreeMap<String,Integer>();
    static {
        MAJOR_STOP_STATION.add("004");
        MAJOR_STOP_STATION.add("008");
        MAJOR_STOP_STATION.add("012");
        MAJOR_STOP_STATION.add("015");
        MAJOR_STOP_STATION.add("018");
        MAJOR_STOP_STATION.add("025");
        MAJOR_STOP_STATION.add("039");
        MAJOR_STOP_STATION.add("034");
        MAJOR_STOP_STATION.add("036");
        MAJOR_STOP_STATION.add("045");
        MAJOR_STOP_STATION.add("041");
        MAJOR_STOP_STATION.add("051");
        MAJOR_STOP_STATION.add("067");
        MAJOR_STOP_STATION.add("070");
        MAJOR_STOP_STATION.add("073");
        MAJOR_STOP_STATION.add("075");
        MAJOR_STOP_STATION.add("077");
        MAJOR_STOP_STATION.add("085");
        MAJOR_STOP_STATION.add("089");
        MAJOR_STOP_STATION.add("093");
        MAJOR_STOP_STATION.add("094");
        MAJOR_STOP_STATION.add("098");
        MAJOR_STOP_STATION.add("100");
        MAJOR_STOP_STATION.add("101");
        MAJOR_STOP_STATION.add("102");
        MAJOR_STOP_STATION.add("103");
        MAJOR_STOP_STATION.add("094");
        MAJOR_STOP_STATION.add("096");
        MAJOR_STOP_STATION.add("098");
        MAJOR_STOP_STATION.add("100");
        MAJOR_STOP_STATION.add("102");
        MAJOR_STOP_STATION.add("106");
        MAJOR_STOP_STATION.add("108");
        MAJOR_STOP_STATION.add("115");
        MAJOR_STOP_STATION.add("118");
        MAJOR_STOP_STATION.add("137");
        MAJOR_STOP_STATION.add("144");
        MAJOR_STOP_STATION.add("146");
        MAJOR_STOP_STATION.add("149");
        MAJOR_STOP_STATION.add("151");
        MAJOR_STOP_STATION.add("158");
        MAJOR_STOP_STATION.add("163");
        MAJOR_STOP_STATION.add("167");
        MAJOR_STOP_STATION.add("172");
        MAJOR_STOP_STATION.add("175");
        MAJOR_STOP_STATION.add("180");
        MAJOR_STOP_STATION.add("185");
        MAJOR_STOP_STATION.add("219");
        
        MAJOR_STOP_STATION_ARRAY = MAJOR_STOP_STATION.toArray(new String[0]);
        for(int i = 0;i < MAJOR_STOP_STATION_ARRAY.length;i++) {
            MAJOR_STOP_STATION_TO_ARRAY_INDEX.put(MAJOR_STOP_STATION_ARRAY[i], Integer.valueOf(i));
        }
    }
}
